name: "Информационные блоки"
description: "Создаем информационные блоки для вставки на страницы сайта"
settings:
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
version: 1.4