name: "Снежинки на сайте"
description: "Добавляет на сайт новогоднее настроение, а точнее снегопад, сугробы и машинку, которая их регулярно убирает!"
settings_params:
  - { variable: countSnowflake, name: "Кол-во снежинок" }
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
version: 1.1