name: "Оплата на карту Банка"
settings:
  - { variable: bank_name, name: "Название Банка" }
  - { variable: card_number, name: "Номер карты" }
  - { variable: card_owner, name: "Владелец карты" }
  - { variable: sms_text, name: "Текст в SMS сообщениии" }
