name: "Наложеный платеж CDEK"
settings_params:
  - { variable: tax, name: "Налоги ИП % (платит покупатель)" }
  - { variable: tax_inside, name: "Налоги ИП % (платит продавец)" }
  - { variable: fee, name: "Комиссия CDEK % (платит покупатель)" }
  - { variable: fee_inside, name: "Комиссия CDEK % (платит продавец)" }
