name: "Автоматическое определение языка"
description: "Предлагает переключиться на язык браузера пользователя, если он доступен на сайте"
settings_params:
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
version: 1.1
