name: "Оплата через OLX"
settings_params:
  - { variable: fee_inside, name: "Комиссия сервиса % (платит продавец)" }
  - {
      variable: fee_fix_inside,
      name: "Комиссия сервиса y.e. (платит продавец)",
    }
  - {
      variable: calculate_finance_payment,
      name: "Пересчитывать финансовый платеж",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
