name: "Заполнение товаров"
description: "Подсчет заполненности карточек товаров"
settings_params:
  - {
      variable: show_menu,
      name: "Показывать в меню",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
menu_section: warehouse
version: 1.4
