controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

extensions_controllers:
    resource: "../hugashop/crm/Extensions/"
    type: attribute
    prefix: "/extension"
