controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

extension_controllers:
    resource: ../hugashop/crm/Extensions/*/Controller/
    type: attribute
    prefix: /test
