name: "Telegram Bot"
type: telegram
settings:
  - { variable: api_key, name: "api key" }
  - { variable: bot_username, name: "Имя бота (без @)" }
  - { variable: secret_token, name: "Секрет" }
  - { variable: admins, name: "Админ бота" }
  - { variable: database, name: "База данных" }
