name: "Подбор конфигурации продукта"
description: "Пошаговый подбор комплектации и расчет стоимости"
settings_params:
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
version: 1.0
