name: "Запрос «Хочу дешевле!»"
description: "Форма запроса более низкой цены."
settings_params:
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
  - {
      variable: show_menu,
      name: "Показывать в меню",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
notifier:
  admin:
    - priceRequestToAdmin: "Запрос на скидку"
version: 1.2
