name: "Запись на шиномонтаж"
description: "Форма записи на шиномонтаж"
settings_params:
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
  - {
      variable: show_menu,
      name: "Показывать в меню",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
menu_section: crm
version: 1.4
